### ISSUE TITLE
typeinfo for ncnn::Layer

### ISSUE THREAD

**Issue by Yoki-pjx** [Qengineering/YoloX-Tracking-ncnn-RPi_64-bit#1]
Hi @Qengineering ,

When I run  the project file YoloX_Byte_Track.cbp, I got following error:

` ||=== Build: Release in YoloX Byte Track (compiler: GNU GCC Compiler) ===|`

`/usr/bin/ld: obj/Release/src/yoloX.o:(.data.rel.ro._ZTI11YoloV5Focus[_ZTI11YoloV5Focus]+0x10)|`
`|undefined reference to 'typeinfo for ncnn::Layer'|`

`||error: ld returned 1 exit status|`

`||=== Build failed: 2 error(s), 0 warning(s) (0 minute(s), 1 second(s)) ===|
`

I have installed Eigen and working with your [RPi 64 Img](https://github.com/Qengineering/RPi-image). I have checked the previous [#1](https://github.com/Qengineering/YoloV5-ncnn-Raspberry-Pi-4/issues/1). It seems not working for me. What is confusing me is that [YoloX detection](https://github.com/Qengineering/YoloX-ncnn-Raspberry-Pi-4) was running on the system with the code 

`yolox.register_custom_layer("YoloV5Focus", YoloV5Focus_layer_creator);
`
It means that my ncnn should be fine to work with YoloX. However, it fails in the tracking program. 
I also checked the Project build options that ncnn library has been added in the compiler. I am not sure which part causes failure this time.

**Comment by Qengineering** [comment]
Before diving into the deep, perhaps an upgrade to the latest ncnn version might help?

**Comment by Yoki-pjx** [comment]
> Before diving into the deep, perhaps an upgrade to the latest ncnn version might help?

It works with the latest ncnn now. Cheers!
