### ISSUE TITLE
Defining Interval for the detector

### ISSUE THREAD

**Issue by jahdkaran** [Qengineering/YoloX-Tracking-ncnn-RPi_64-bit#3]
Hi, 
Is there any way to define an interval for the detector model, And leave the tracker to do the hard work in those intervals? 
similar to [this issue](https://github.com/nwojke/deep_sort/issues/167) but with a different tracker.

**Comment by Qengineering** [comment]
@jahdkaran,

Ultimately it is possible. However, it will take quite a bit of effort to modify BYTETracker to deal with no new location input, just to predict the next position. At the moment we don't have time to change the code.
